CREATE WAREHOUSE IF NOT EXISTS SPOTIFY_WH WITH WAREHOUSE_SIZE='x-small';
CREATE DATABASE IF NOT EXISTS SPOTIFY_DB;
CREATE SCHEMA IF NOT EXISTS SPOTIFY_DB.BRONZE;

SHOW WAREHOUSES;

-- Bronze Layer
-- count (20-FEB-2025(1:14 AM): 190)
SELECT COUNT(*) FROM SPOTIFY_EVENTS_BRONZE;

USE SCHEMA BRONZE;
SELECT * FROM SPOTIFY_EVENTS_BRONZE;



-- Silver Layer
-- Create a new schema for Silver layer
CREATE SCHEMA IF NOT EXISTS SPOTIFY_DB.TRANSFORM;

USE WAREHOUSE SPOTIFY_WH;
USER DATABASE SPOTIFY_DB;
SELECT * FROM TRANSFORM.SPOTIFY_SILVER;


-- Gold Layer
-- Create new schema for Bronze Layer
CREATE SCHEMA IF NOT EXISTS SPOTIFY_DB.MART;
USE SCHEMA MART;

SELECT * FROM MART.TOP_SONGS;
