WITH BRONZE_DATA AS (
SELECT
    EVENT_ID, 
    USER_ID,
    SONG_ID,
    ARTIST_NAME, 
    SONG_NAME,
    EVENT_TYPE, 
    DEVICE_NAME,
    COUNTRY,
    TO_TIMESTAMP_TZ(TIMESTAMP) AS EVENT_TS
FROM 
    {{
        source('bronze', 'spotify_events_bronze')
    }}
)

SELECT 
    EVENT_ID, 
    USER_ID,
    SONG_ID,
    ARTIST_NAME, 
    SONG_NAME,
    EVENT_TYPE, 
    DEVICE_NAME,
    COUNTRY,
    EVENT_TS
FROM
    BRONZE_DATA
WHERE EVENT_ID IS NOT NULL AND USER_ID IS NOT NULL AND SONG_ID IS NOT NULL AND EVENT_TS IS NOT NULL