{{ 
    config(
        schema='mart'
    ) 
}}

SELECT
    USER_ID,
    DEVICE_NAME AS DEVICE_TYPE,
    COUNTRY,
    COUNT(CASE WHEN EVENT_TYPE = 'play' THEN 1 ELSE 0 END) AS TOTAL_PLAYS,
    COUNT(CASE WHEN EVENT_TYPE = 'skip' THEN 1 ELSE 0 END) AS  TOTAL_SKIPS,
    COUNT(CASE WHEN EVENT_TYPE = 'add_to_playlist' THEN 1 ELSE 0 END) AS  PLAYLIST_ADDS,
    EXTRACT(DAY FROM EVENT_TS) AS DAY
FROM 
{{
    ref('spotify_silver')
}}
GROUP BY USER_ID, DEVICE_NAME, COUNTRY, EXTRACT(DAY FROM EVENT_TS)
ORDER BY TOTAL_PLAYS DESC